name: dart_compilers_playground
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  characters: ^0.5.0
  quiver: ^2.1.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.6
